### ISSUE TITLE
feat: Opaque Token Introspector 메타데이터화

### ISSUE THREAD

**Issue by rudeh1253** [team-HF/HF_backend#23]
## 개요

Opaque Token에 대한 정보를 메타데이터로 만들어서 추후 소셜 로그인 요구사항이 추가될 경우 유연하게 대처할 수 있도록 한다.
Opaque Token의 Authorization Server URL, Endpoint, Response Body 구조, Request 명세를 JSON 혹은 YAML로 정리하면 애플리케이션에서 메타데이터를 읽고 사용할 수 있도록 한다.

### 예시
```yaml
oauth2spec:
  - name: google
    auth-server: GOOGLE
    client-id: ${secret.oauth2.google.client-id}
    client-secret: ${secret.oauth2.google.client-secret}
    endpoints:
      grant-token: # 인가코드를 가지고 Access Token, Refresh Token, Email을 발급받는 Endpoint
        request:
          url: https://oauth2.googleapis.com/token
          method: POST
          headers:
            - name: Accept
              value: application/json
          body:
            code: /code/
            redirect-uri: /redirectUri/
            client-id: ${secret.oauth2.google.client-id}
            client-secret: ${secret.oauth2.google.client-secret}
            grant-type: authorization_code
        response:
          body:
            access-token: access_token
            refresh-token: refresh_token
```
